[markata]
assets_dir = "static"
icon = "me.jpg"
description = "Stable Diffusion image store"
url = "https:/pypeaday.github.io/stable-diffusion-pype-dev"
body_width='100vw'
edit=false

color_link = "#64a1dd"
color_accent = "#83dcc8cc"
color_bg = '#1f2022'
color_text = '#d8ebe6'



hooks = [
"markata.plugins.base_cli",
"markata.plugins.tui",
"markata.plugins.copy_assets",
"markata.plugins.feeds",
"stable_diffusion_pype_dev.load"
]

[[markata.head.text]]
value = """
<style>
img {
width: 100%;
height: auto;
}
ul {
  display: flex;
  flex-wrap: wrap;
}

li {
  flex: 1 2 400px;
}
</style>

"""


[markata.feeds.archive]
title="archive"
filter="True"
reverse="True"
card_template="""
<li class='post'>
    <a href='/stable-diffusion-pype-dev/{{ title }}'>
        <img src='/stable-diffusion-pype-dev/{{ title }}' height='{{ height }}' width='{{ width }}' alt='{{ prompt }}'>
    </a>
    <details>
        <summary> filter </summary>
        {{ app_source }} 
    </details>
    <details>
        <summary> command </summary>
        {{ command }} 
    </details>
</li>
"""


[markata.feeds.automatic1111]
title="Automatic1111"
filter="'automatic1111'in app_source"
reverse="True"
card_template="""
<li class='post'>
    <a href='/stable-diffusion-pype-dev/{{ title }}'>
        <img src='/stable-diffusion-pype-dev/{{ title }}' alt='{{ prompt }}'>
    </a>
    <details>
        <summary> filter </summary>
        {{ app_source }} 
    </details>
    <details>
        <summary> command </summary>
        {{ command }} 
    </details>
</li>
"""

[markata.feeds.olivet]
title="Olivet"
filter="'Genesis'in command"
reverse="True"
card_template="""
<li class='post'>
    <a href='/stable-diffusion-pype-dev/{{ title }}'>
        <img src='/stable-diffusion-pype-dev/{{ title }}' height='{{ height }}' width='{{ width }}' alt='{{ prompt }}'>
    </a>
    <details>
        <summary> filter </summary>
        {{ app_source }} 
    </details>
    <details>
        <summary> command </summary>
        {{ command }} 
    </details>
</li>
"""

[[markata.head.meta]]
name = "theme-color"
content="#64A1DD"

[[markata.head.meta]]
name = "twitter:creator"
content="@pypeaday"

[[markata.head.meta]]
name = "og:type"
content = "article"

[[markata.head.meta]]
name = "og:author"
content = "Pypeaday"

[[markata.head.meta]]
name = "og:site_name"
content = "Pypeaday"


[markata.prevnext]
prevnext_color_angle = "#ff66c4"
